Use gevent.subprocess if gevent if installed
gevent monkeypatches select.poll away, so normal
python subprocess module does not work.

This causes this error:

Fix AttributeError: 'module' object has no attribute 'poll'

when testing ia-wrapper with cython and gevent installed.

We need to patch all files using subprocess
because pytest does not seem to restore module's health
across files.